### ISSUE TITLE
packages not found

### ISSUE THREAD

**Issue by dbrimley** [ouyi/docker-ubuntu32-firefox#2]
When running the Dockerfile....

```
Step 7 : RUN apt-get -y install iputils-ping firefox openjdk-7-jre icedtea-7-plugin libpango1.0-0 libxft2 libxmu6 libxv1 fonts-takao
 ---> Running in b17ad4a63dab
Reading package lists...
Building dependency tree...
Reading state information...
Package openjdk-7-jre is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'openjdk-7-jre' has no installation candidate
E: Unable to locate package icedtea-7-plugin
E: Unable to locate package fonts-takao
```

**Comment by ouyi** [comment]
Hi David,

I could not reproduce the issue by re-triggering the build on docker hub. Here is the successful build: https://hub.docker.com/r/ouyi/docker-ubuntu32-firefox/builds/bsemmbsgaxqaonryznjpxsk/

However, I saw the issue before:
https://hub.docker.com/r/ouyi/docker-ubuntu32-firefox/builds/brlkx5h6f5zcojnuvagrrmn/
which seemed to be a temporary issue, because the log states:
```
Err http://archive.ubuntu.com precise Release.gpg
  Temporary failure resolving 'archive.ubuntu.com'
```
Are you seeing the same message in your build log?

**Comment by dbrimley** [comment]
You were right, that was the problem.  I cleaned things up and it starts firefox now.
